H2 track
Yanina-31/Spotify_Service pull request #10
Opened 2021-11-10 05:30 UTC by Yanina-31

no funciona del todo pero me compila, lo seguiré trabajando a este código!

2021-11-11 19:31 UTC, mrojasabregu requested changes
Subamos código no comentado

2021-11-11 19:31 UTC, mrojasabregu commented on clase 2/spotify-service/src/main/java/com/spotify/spotify/service/controller/GlobalControllerAdvice.java
> +    /*@ResponseStatus(HttpStatus.BAD_REQUEST)
Por que subiste todo comentado?

2021-11-11 19:31 UTC, mrojasabregu commented on clase 2/spotify-service/src/main/java/com/spotify/spotify/service/service/IArtistaService.java
> +    /*List<Track> getTracks();
no subamos codigo comentados

2021-11-11 20:10 UTC, Yanina-31 commented
ese dia se me había roto todooo e intente volver a la rama anterior y no me
funcionaba ya lo solucione ahora en breve hago pull request.
Perdón!

El jue, 11 nov 2021 a las 16:31, Matias Rojas ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Subamos código no comentado
> ------------------------------
>
> In clase
> 2/spotify-service/src/main/java/com/spotify/spotify/service/controller/GlobalControllerAdvice.java
> <https://github.com/Yanina-31/Spotify_Service/pull/10#discussion_r747763283>
> :
>
> > @@ -26,4 +26,59 @@
>
>          });
>
>          return errors;
>
>      }
>
> +
>
> +    ***@***.***(HttpStatus.BAD_REQUEST)
>
>
> Por que subiste todo comentado?
> ------------------------------
>
> In clase
> 2/spotify-service/src/main/java/com/spotify/spotify/service/service/IArtistaService.java
> <https://github.com/Yanina-31/Spotify_Service/pull/10#discussion_r747763831>
> :
>
> > @@ -17,7 +17,7 @@
>
>
>
>      Artista deleteArtista(Long artistId);
>
>
>
> -    List<Track> getTracks();
>
> +    /*List<Track> getTracks();
>
>
> no subamos codigo comentados
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Yanina-31/Spotify_Service/pull/10#pullrequestreview-804146511>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUBJPFQULU6TGN6CQP7OM63ULQKZ5ANCNFSM5HW76UHA>
> .
>

2021-11-12 15:01 UTC, maalbera approved these changes

2021-11-12 15:01 UTC, maalbera commented on clase 2/spotify-service/src/main/java/com/spotify/spotify/service/service/impl/ArtistaService.java
> +    /*public Iterable<Track> getTracks() {
No subir codigo comentado

2021-11-12 16:42 UTC, Yanina-31 commented on clase 2/spotify-service/src/main/java/com/spotify/spotify/service/controller/GlobalControllerAdvice.java
> +    /*@ResponseStatus(HttpStatus.BAD_REQUEST)
listo ya fue eliminado

2021-11-12 16:42 UTC, Yanina-31 commented on clase 2/spotify-service/src/main/java/com/spotify/spotify/service/service/IArtistaService.java
> +    /*List<Track> getTracks();
listo ya lo elimine.

2021-11-12 16:42 UTC, Yanina-31 commented on clase 2/spotify-service/src/main/java/com/spotify/spotify/service/service/impl/ArtistaService.java
> +    /*public Iterable<Track> getTracks() {
eliminado

2021-11-12 16:43 UTC, merged